#!/bin/bash

# Enable tracing of command invocations
# set -x

if [ "$#" -lt 1 ]; then
  BASE_DIR=$( cd "$(dirname $0)/..)" ; pwd -P )
else
  BASE_DIR="$1"
fi

echo "BASE_DIR: $BASE_DIR"

VIRTENV_NAME=virtualenv

# This requires the "virtualenv" package to be installed

cd "$BASE_DIR"

echo "Creating virtualenv $VIRTENV_NAME (in $BASE_DIR/$VIRTENV_NAME)"
virtualenv --clear -p $(which python3.6) $BASE_DIR/$VIRTENV_NAME

source $VIRTENV_NAME/bin/activate

pip install -r requirements.txt

echo "DONE."
echo "-------------------------------------------------------------------------------"
echo "Enter \"source $VIRTENV_NAME/bin/activate\" to enter the virtual environment"
echo " and \"deactivate\" to exit"
echo "-------------------------------------------------------------------------------"

